# Generated by Django 2.2.6 on 2020-02-14 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_car_car_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='The name must be written in Cyrillic and not more than 50 characters!', regex='^[А-Яа-я ]{0,50}$')]),
        ),
    ]
