# Generated by Django 2.2.6 on 2020-02-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200214_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='des_time',
            field=models.TimeField(),
        ),
    ]
