# Generated by Django 2.2.6 on 2020-02-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200214_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['model']},
        ),
        migrations.AlterField(
            model_name='car',
            name='car_num',
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
    ]
