# Generated by Django 2.2.6 on 2020-02-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('service', '0006_auto_20200215_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dispatcher',
        ),
    ]
