# Generated by Django 2.2.6 on 2020-02-15 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20200215_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 2, 15, 12, 50, 51, 228721, tzinfo=utc)),
        ),
    ]
