# Generated by Django 2.2.6 on 2020-02-15 19:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status', '-date']},
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 2, 15, 19, 55, 48, 450057, tzinfo=utc)),
        ),
    ]
