# Generated by Django 2.2.6 on 2020-02-15 19:56

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20200215_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 2, 15, 19, 56, 50, 940897, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='The name must be written in Cyrillic and not more than 50 characters!', regex='^[А-Яа-я ]{5,50}$')]),
        ),
    ]
